SCR_MissionHeaderCampaign {
 m_sName " Everon PVE Conflict"
 m_sAuthor "JLH + INF_Mike64"
 m_sDescription "Join the Iron-Fists in their mission to liberate the region from invading Russian forces. <br/><br/>Mode: Conflict PvE<br/>Era: Modern<br/>Mods: ACE & RHS<br/>Person: 1st (with vehicle mirrors and periscopes)<br/><br/>Enjoy playing with our members? Why not do a trial mission with us. Learn more: https://iron-fists.co.uk/"
 m_sDetails "Join the Iron-Fists in their mission to liberate the region from invading Russian forces. <br/><br/>Mode: Conflict PvE<br/>Era: Modern<br/>Mods: ACE & RHS<br/>Person: 1st (with vehicle mirrors and periscopes)<br/><br/>Enjoy playing with our members? Why not do a trial mission with us. Learn more: https://iron-fists.co.uk/"
 m_sIcon "{0DE93D6950C6E676}Art/Eden_Loading.edds"
 m_sLoadingScreen "{0DE93D6950C6E676}Art/Eden_Loading.edds"
 m_sPreviewImage "{0DE93D6950C6E676}Art/Eden_Loading.edds"
 m_iPlayerCount 32
 m_fXpMultiplier 0.6
 m_WCS_LoadoutEditor_Settings WCS_LoadoutEditor_Settings "{69C29B4DEE3F3793}" {
 }
 m_WCS_Core_Settings WCS_Core_Settings "{69D959CF8D86F401}" {
  m_bIsTeamBalancerEnabled 0
  m_iMaxTeamImbalance 52
 }
 m_iStartingHQSupplies 30
}