SCR_EntityCatalogMultiList {
 m_aMultiLists {
  SCR_EntityCatalogMultiListEntry "{61835C0062A55061}" {
   m_aEntities {
    SCR_EntityCatalogEntry "{62D2F3D367FF2E38}" {
    }
    SCR_EntityCatalogEntry "{6A10760C484559B1}" {
     m_sEntityPrefab "{CEFC2B5C4334CADB}Prefabs/Vehicles/Wheeled/TIGR/AGS/GAZ_TIGR_v2_AGS17_PAG17.et"
    }
    SCR_EntityCatalogEntry "{6A10760C5B320816}" {
     m_sEntityPrefab "{7A21F47E09038E58}Prefabs/Vehicles/Wheeled/TIGR/ArbaletDM/GAZ_TIGR_v2_Arbalet_KORD.et"
    }
    SCR_EntityCatalogEntry "{6A10760C632167B2}" {
     m_sEntityPrefab "{70BF53CF0F4D103F}Prefabs/Vehicles/Wheeled/TIGR/ArbaletDM/GAZ_TIGR_v2_Arbalet_PKM.et"
    }
    SCR_EntityCatalogEntry "{6A10760C6433F4B0}" {
     m_sEntityPrefab "{CD4737303AA14C6D}Prefabs/Vehicles/Wheeled/TIGR/KORD/GAZ_TIGR_v2_KORD_SPP.et"
    }
    SCR_EntityCatalogEntry "{6A10760C6C605C74}" {
     m_sEntityPrefab "{7ACFD8FA081996F6}Prefabs/Vehicles/Wheeled/TIGR/PKP/GAZ_TIGR_v2_PKM_1P29.et"
    }
    SCR_EntityCatalogEntry "{605098A49FEFA106}" {
    }
    SCR_EntityCatalogEntry "{657524254F1AEDDD}" {
    }
    SCR_EntityCatalogEntry "{6575242530334CC7}" {
    }
    SCR_EntityCatalogEntry "{657524253FB28686}" {
    }
    SCR_EntityCatalogEntry "{6575242500F5D322}" {
    }
    SCR_EntityCatalogEntry "{6575242501E1A20F}" {
    }
    SCR_EntityCatalogEntry "{657524253E819E8E}" {
    }
    SCR_EntityCatalogEntry "{657524251A1DFBA0}" {
    }
    SCR_EntityCatalogEntry "{657524251AC46C49}" {
    }
    SCR_EntityCatalogEntry "{657524254C384B41}" {
    }
    SCR_EntityCatalogEntry "{65752424F08293ED}" {
    }
    SCR_EntityCatalogEntry "{65752424E8FA959A}" {
    }
    SCR_EntityCatalogEntry "{65752424FD2BDA40}" {
    }
    SCR_EntityCatalogEntry "{6A10760FFB97EE32}" {
     m_sEntityPrefab "{1EF865DC4E3F7E0B}IFV/BMP2/BMP2_Olive_test.et"
    }
    SCR_EntityCatalogEntry "{6A10760F822DB158}" {
     m_sEntityPrefab "{BC07885176C7FF8A}Prefabs/Vehicles/Tracked/T-72A/T72A_base.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6A10760F9560E62F}" {
     m_sEntityPrefab "{D9EB40D7AD0966EC}Prefabs/Vehicles/Tracked/T-72B/T72B_FIA.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6A10760FA24B6540}" {
     m_sEntityPrefab "{42006D6F4D765E57}Prefabs/Vehicles/Tracked/T90M/T90M_Proryv3_Full.et"
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6A10760FD1B8C5F4}" {
     m_sEntityPrefab "{48BB423641D40E77}Prefabs/Vehicles/Tracked/T14/Tank_T14.et"
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6A10760FE38E59D4}" {
     m_sEntityPrefab "{DA89CD22F7A369F6}Prefabs/Vehicles/Tracked/Kurganets25/Kurganets25_Kord.et"
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
    SCR_EntityCatalogEntry "{6A10760FEE63662F}" {
     m_sEntityPrefab "{B73C7716E00B4BC3}Prefabs/Vehicles/Tracked/Kurganets25/Kurganets25_57mm.et"
     m_bEnabled 0
     m_aEntityDataList {
      SCR_EntityCatalogSpawnerData "{65752424FD2BDAE9}" {
       m_eSlotTypes VEHICLE_LARGE
      }
     }
    }
   }
  }
 }
}