SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Machine Guns (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{698B05B6DBE96906}" {
   m_sEntityPrefab "{441C6358A2167AE3}Prefabs/Weapons/MachineGuns/M240/MG_M240_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B6DBE9F0D5}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 80
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{698B05B6DBE9F0D1}" {
       m_vItemOffset 0 0 -0.15
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{698B05B6DBE9F0D0}" {
   m_sEntityPrefab "{BA87F78D0E7E3A90}Prefabs/Weapons/MachineGuns/M240/MG_M240_Light_MDO.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B6DBE9F0D3}" {
     m_eItemType MACHINE_GUN
     m_eItemMode WEAPON
     m_iSupplyCost 80
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{698B05B6DBEE7747}" {
       m_vItemOffset 0 0 -0.15
      }
     }
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}