SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (Reforger)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{698B05B61847D476}" {
   m_sEntityPrefab "{81EB948E6414BD6F}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B61847D477}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 60
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{698B05B3C78FD27E}" {
   m_sEntityPrefab "{F765DED3699B6B4C}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII_OliveGreen_Sand_Stripes.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B3C78FD233}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 60
     m_eRequiredRank CORPORAL
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{698B05B3C68CA7BB}" {
   m_sEntityPrefab "{DD17D4BC320A94C8}Prefabs/Weapons/Rifles/M14/Rifle_M21_ARTII_OliveGreen_Sand_Stripes_Wrapped.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B3C68CA773}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 60
     m_eRequiredRank SERGEANT
    }
   }
  }
 }
}