SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Carbine Rifles (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{698B05B69CE2B988}" {
   m_sEntityPrefab "{139B1F6E64109536}Prefabs/Weapons/Rifles/M16/variants/Rifle_M16A2_carbine_weaver_EOT_pmag.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B69CE2B98F}" {
     m_eItemMode WEAPON
     m_iSupplyCost 12
    }
   }
  }
  SCR_EntityCatalogInventoryItem "{698B05B69CE33EBD}" {
   m_sEntityPrefab "{2F48F6DD0A593BA0}Prefabs/Weapons/Rifles/M16/variants/Rifle_M16A2_weaver_marksman.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B69CE33EBE}" {
     m_eItemMode WEAPON
     m_iSupplyCost 12
    }
   }
  }
 }
}