SCR_EntityCatalogMultiListEntry {
 m_sIdentifier "Weapons - Snipers (RHS)"
 m_aEntities {
  SCR_EntityCatalogInventoryItem "{698B05B61D819DD3}" {
   m_sEntityPrefab "{8909A91CFF369BB3}Prefabs/Weapons/Rifles/M40/Rifle_M40A5_Optic.et"
   m_aEntityDataList {
    SCR_ArsenalItem "{698B05B61D819DD0}" {
     m_eItemType SNIPER_RIFLE
     m_eItemMode WEAPON_VARIANTS
     m_iSupplyCost 1
     m_aArsenalDisplayData {
      SCR_ArsenalItemDisplayData "{698B05B61D819DD1}" {
       m_vItemOffset 0 0 -0.2
      }
     }
     m_eRequiredRank LIEUTENANT
    }
   }
  }
 }
}